Repository coala/landing-frontend, pull requests merged in 2018-10, with the labels that each got.

#287 Added copy to clipboard functionality
  index.html
  partials/tabs/coalaonline.html
  resources/js/Directives/coalaOnlineDirective.js
  vendors/clipboard.js/clipboard.min.js
Labels: difficulty/newcomer, process/approved, size/XS

#288 moban: Sync Moban Templates
  .gitignore
Labels: process/approved, size/XS

#285 Make code examples on homepage bookmarkable
  partials/tabs/home.html
  resources/js/app.js
Labels: area/documentation, difficulty/newcomer, process/approved, size/XS
